title: Bri Hatter
subtitle: Junior Full Stack developer
description: >- # this means to ignore newlines until "baseurl:"
  Specializing in Java, JavaScript | React, Spring Boot, Django | MySQL Workbench.

url: "https://graybeggar.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    # - text: Shop
    #   url : /shop
    # - text: Contact
    #   url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Bri Hatter
author_bio: Full-stack developer with hands-on experience building responsive, accessible web applications using Java, JavaScript, React, HTML/CSS, and Jest. Strong background in managing projects, solving problems under pressure, and translating real-world needs into functional software solutions. Passionate about joining a forward-thinking team where I can contribute to clean, user-focused code and continue developing robust technical solutions.
author_email: "blhat@hotmail.com"
author_location: USA
resume_url: "https://docs.google.com/document/d/15_aozlre2mso24XRB9QuZnnOQQurnlZUaV6bYH6mWwk/edit"
typewrite-text: Junior Full Stack developer specializing in Java, JavaScript | React, Spring Boot, Django | MySQL Workbench
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: APC
              company_logo: APC.png
              company_url: https://apcisg.com/services/automotive-product-consultants/
              designation: Sales Rep/ Assistant
              # description: Worked on various Google Products
              visibility: true
            - company_name: DISH Network
              company_logo: dish_network_logo.png
              company_url: https://dish.com/isg/
              designation: Retention Agent
              # description: Worked on various Azure Cloud Products
              visibility: true

# Education
author_education_details:
              - college_logo: launchcode_logo.png
                college_name: LaunchCode
                college_url: https://www.launchcode.org/
                college_degree: Full-Stack Developer
                # description: Bachelor of Technology
                visibility: true
              - college_logo: full_sail_university_logo.png
                college_name: Full Sail University
                college_url: https://hello.fullsail.edu/
                college_degree: Bachelor's in Computer Science
                description: Bachelor of Computer Animation
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: home-botanicals-screenshot.png
                project_title: Home Botanicals Bible
                project_description: A plant care app that allows users to explore plants, track care tasks, and build a personalized digital garden. Designed and implemented “My Garden” feature using useState, useEffect, and localStorage to persist user data. Created a dynamic FeaturedPlants component to showcase a new plant each day based on seeded randomness. Built responsive layouts using CSS Grid and Flexbox with accessibility in mind. Full Project Tech Stack - React, JavaScript, HTML, CSS, localStorage
                project_url: https://home-botanicals-bibile.netlify.app/
                visibility: true

# social links
# twitter_username: johndoe
github_username:  Graybeggar
# instagram_username: johndoe
# facebook_username: johndoe
linkedin_username: bri-hatter-9aa869151
# behance_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: johndoe
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: johndoe

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: blhat@hotmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

  # jekyll admin is causing issues with github pages, so it's disabled by default
  # - jekyll-admin 

# Jekyll Admin Config
# jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  # homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
